DATAGRAM_MESSAGE_SIZE = 1000

DATAGRAM_SIZE = 1024

DATAGRAM_TIMEOUT_SECONDS = 10

IS_FRAGMENTED_BIT_FLAG = 7
IS_ACK_BIT_FLAG = 6
IS_LAST_FRAGMENT_BIT_FLAG = 5

SEQUENCE_NUMBER_START_INDEX = 0
SEQUENCE_NUMBER_LENGTH = 4

FLAGS_BYTE_INDEX = 4

FRAGMENT_OFFSET_START_INDEX = 5
FRAGMENT_OFFSET_LENGTH = 8

FRAGMENTATION_ID_START_INDEX = 13
FRAGMENTATION_ID_LENGTH = 8

PAYLOAD_START_INDEX = 21
